# Generated by Django 4.0 on 2021-12-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):   

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll_number', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=20)),
            ],
        ),
    ]
