# Generated by Django 4.0 on 2021-12-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdata',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
