# Generated by Django 4.0 on 2021-12-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherdata', '0002_alter_teacherdata_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdata',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
